### PR TITLE
Fixing extension name for newsholder page

### PR DESCRIPTION
**Pull request by spekulatius**
Hello @sheadawson 

The name of the extension wasn't correct as far as I can tell. Can you verify this and maybe merge it in?

Spek

### CODE REVIEW

**Comment by sheadawson** [comment]
Thanks actually this can be removed now as the lumber jack extension is applied in NewsHolder.php

**Comment by sheadawson** [comment]
Fixed in 8b1751a831987ca31fdeaee769ac3609e303ee7e

**Comment by spekulatius** [comment]
Yupp, I saw that later on too.

**Comment by spekulatius** [comment]
Do you want to publish a new release so people with stable pref get this change @sheadawson ?

**Comment by sheadawson** [comment]
I do, I'll get to it later today ;)

On Tue, Dec 8, 2015 at 9:33 AM, Peter Thaleikis notifications@github.com
wrote:

> Do you want to publish a new release so people with stable pref get this
> change @sheadawson https://github.com/sheadawson ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sheadawson/silverstripe-newsly/pull/4#issuecomment-162652697
> .

## 

_Shea Dawson_
Web Developer
LiveSource

_mobile_ +64 20 4028 5647
_skype_ squatchnz
_email_ shea@livesource.co.nz
*web *www.livesource.co.nz

**Comment by spekulatius** [comment]
Thanks :)

**Pull request closed without merging**
